### PR TITLE
feat: add s11 and s12 support

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Describe what you did and why.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by YogevBokobza** [comment]
Now S11 lights (turn off and turn on) is working!
Continue to work..

**Comment by YogevBokobza** [comment]
Update: Fully working S11

Left to do:
- Implement set child lock capability
- Align all the test to work

@TomerFi  Please see if this current logic where device type is implemented inside 'self' object is ok.
This change is must because of varaiaty of Switcher devices of the same type such as Runner, Runner S11 etc..

**Comment by YogevBokobza** [comment]
Update:
Tests are now passing.
Going to work on child lock and later on I will add s12 support

**Comment by YogevBokobza** [comment]
@TomerFi  Can you fix current issue with found leak in test?
Its just testing token so the tests can pass.
Just put it in ignore in GitGuardian

**Comment by YogevBokobza** [comment]
@thecode Can you help with this PR? @TomerFi  is never here..

**Comment by thecode** [comment]
I am not a maintainer in this repository, but even if I did I would ask you to split it into small PRs as it is not possible for me to review such a large PR and discuss again with Switcher for an option to remove the need for Token and maybe replace it with a dialog in Home Assistant that the user confirm the usage.

This whole Token thing doesn't align with Switcher claiming for local access (I know once you get the token you can use local API) but what will happen if Switcher close their business in the future? 

It will also make it difficult for users to know if they need token or not, all my devices for now doesn't need token, so what is expected from me as a user? should I be presented with a dialog for token while I don't need it? 

And final note, for Switcher Breeze, Switcher insisted we need to get data from their server and eventually agreed to find a solution which allows us to work without access to their server.

**Comment by YogevBokobza** [comment]
@thecode I am communicating tightly with one of the Switcher devs.. A token is a must for security hardening..
The token will be a must in the near future for all devices.
I open the PR in Home Assistant as well to support this.

Without your help there and @TomerFi  or whoever is responsible here Runner S11, S12, and Switcher Lights won't be possible to ever work.
Also in the near future none of the devices would work.

I need your cooperation here.
If needed I am available on a phone call.

**Comment by YogevBokobza** [comment]
Also, Small PR won't work because its all connected to each other.

**Comment by thecode** [comment]
> @thecode I am communicating tightly with one of the Switcher devs.. A token is a must for security hardening.. The token will be a must in the near future for all devices. I open the PR in Home Assistant as well to support this.

I don't understand what is "will be a must in the near future for all devices", are they going to remotely change the firmware on my device and break it without my permission?

> Without your help there and @TomerFi or whoever is responsible here Runner S11, S12, and Switcher Lights won't be possible to ever work.

I stated from my first ever call with Switcher that I will help on HA when I have time, but I don't have the capacity to work on the PyPI package. when this is ready I can try to help on the HA side with the integration. 

> Also in the near future none of the devices would work.

I do hope it won't happen for existing devices, when this happens I am going to remove the integration from HA.

**Comment by YogevBokobza** [comment]
@thecode Regarding what you were saying, The Switcher dev said that:
The Token purpose is at the moment, only used by the Smart Shutters from some version and above to make another layer of security for the products and to prevent unwanted access from others with access to our local network.

Regarding the Breeze, He said he already gave you the database for local usage and he said that he will send an updated database from time to time.

Plus, He said, Switcher has above 30k users and she won't vanish that easily.

**Comment by TomerFi** [comment]
Looks like the same CI job fails constantly, I recommend going over the [workflow](https://github.com/TomerFi/aioswitcher/blob/dev/.github/workflows/pr.yml) and verifying this works prior to pushing.

**Comment by YogevBokobza** [comment]
@TomerFi  Can you fix the "GitGuardian Security Checks" from your side?
The token that is there is fake for tests only

**Comment by YogevBokobza** [comment]
@TomerFi  For me locally everything is working.
The 2 things that are blocking now are the poetry being changed all the time and "GitGuardian Security Checks" You need to manually allow that findings.

**Comment by TomerFi** [comment]
@YogevBokobza First of all, thank you for the time and effort put in this PR.

For clarification, _GitGuardian_ runs as a standalone workflow, it wasn't the one preventing the rest of the workflows from running, that was caused by the Lint job failure, which you resolved in your latest commits.

As for reviewing, as mentioned in this project's README, we are looking for contributors and maintainers. Sorry, but for various reasons, I will not have the capacity to review a PR this big anytime soon. That being said, before anyone else can review this, I would recommend:
- As mentioned earlier, smaller PRs go a long way.
- Trim down the 45 commits because unless I'm mistaken, it looks like they address only 1 concern.
- There are a lot of going on here, it's hard to stay focused, consider opening a new PR in order to clear the clutter.

As for the usage of the token, I agree with the @thecode on this. We should strive to find a solution that doesn't involve accessing the vendor's servers. This library was working locally only from the time it was created, changing this now is a huge step that should not be taken lightly. @thecode is pretty much this library's only contact to the vendor, and  he is the only maintainer of the _Home Assistant_ integration, which is this library's biggest client by far. Obviously, this kind of change in _Aioswitcher_ should be inline with the _Home Assistant_ integration, so please take his comments into consideration.

**Comment by YogevBokobza** [comment]
@TomerFi @thecode
Regarding the token, I talked with the Switcher dev regarding that and he wanted to clear that:

**The Token is ONLY used Locally communicating with the devices by TCP. The Token Do Not Used for any communication with Switcher Servers**

As far as for this PR length, This all logic serve as one. splits this PR means the logic would be break as everything is relating to each other.

All the current is tested with my own devices.
I got Runner S11 and S12 and they both working now.

The community is waiting badly for Runner S11,S12 and Light support.

Please, dont make this more hard and communicate.

How do you want to proceed?

**Comment by YogevBokobza** [comment]
@TomerFi  @thecode
Also to mention, I have PR on Home Assistant core to support this new code as well.
I keep update here and there at the same time.

**Comment by YogevBokobza** [comment]
@TomerFi Can you review it?

**Comment by YogevBokobza** [comment]
I am closing this PR as it's not going to be merged because of its size.
I am making smaller PRs using this PR code.

Please don't delete the branch for now.

**Pull request closed without merging**
