### PR TITLE
fix: fix mac address for type2

### LINKED ISSUE #783: Incorrect parsing of MAC address for Switcher Runner
### What happened?

Details in https://github.com/home-assistant/core/issues/122715#issuecomment-2254539132, it looks like we have a one byte shift when parsing the MAC address for Switcher Runner.
@YogevBokobza you recently checked all runner devices, can you verify that?

### Module Version

3.4.3

### Device Type

Switcher Runner

### Firmware Version

1.79

### Relevant log output

```shell
39:E8:68:E7:80:3B
3C:E8:68:E7:80:3B
3F:E8:68:E7:80:3B
49:E8:68:E7:80:3B
```
The real device MAC starts with `E8` so the first byte is not related to the MAC
```

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Describe what you did and why.

**Related issue (if any):** fixes #783

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by YogevBokobza** [comment]
@thecode 
Will this fix work for HA? how does it retrieve the MAC there?

** UPDATE ** tested in HA and it's working..

**Comment by YogevBokobza** [comment]
@thecode 
I just wonder how we didn't see this in HA until now.. it looks like an old issue..

**Comment by thecode** [comment]
> @thecode I just wonder how we didn't see this in HA until now.. it looks like an old issue..

We did, there were few reports of it, the shift itself is not creating a problem as long as the left bits are not changing so most people probably doesn't notice it.

I looked at the message history, this was reported to Switcher on the 30/11/2022, they said they will check and report back (still waiting...)

**Review by thecode — APPROVED** [review]
Thanks!

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
@YogevBokobza - Thank you!

**Pull request merged**
