### PR TITLE
fix: make types-requests a dev dependency

### LINKED ISSUE #791: types-requests incompatibility with HA
### What happened?

#780 introduced a dependency on `types-requests = "^2.31.0.6"`
https://github.com/TomerFi/aioswitcher/blob/841fd6c7ee3748507af9810fdba659f6e2f51de6/pyproject.toml#L23-L26

But HA has it pinned to `2.31.0.3`
https://github.com/home-assistant/core/blob/8cfac68317288fcb88888e369d3bd4302037b77b/requirements_test.txt#L52

It caused issues in my dev environment, preventing me from running the "Install all test requirements" task.

Although it was easily solved - I am surprised that it is a dependency at all....
Should it not be a dev/test-dependency only?

cc @YogevBokobza / @thecode 

### Module Version

4.0.0

### Device Type

Switcher V2

### Firmware Version

.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by epenet**
## Description

> Describe what you did and why.

**Related issue (if any):** fixes #791

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by TomerFi** [comment]
Thank you @epenet - LGTM!
We need to rebase and solve the conflict before merging.

**Comment by epenet** [comment]
> Thank you @epenet - LGTM! We need to rebase and solve the conflict before merging.

Conflict resolved

**Review by thecode — APPROVED** [review]
@YogevBokobza I think we should move to `aiohttp` in a future PR as this library is all async except for a single method which is now not async that uses `requests`

**Review by TomerFi — APPROVED** [review]

**Comment by thecode** [comment]
@TomerFi can you release a patch version with this fix? I will bump it in HA. Thanks

**Comment by TomerFi** [comment]
> @YogevBokobza I think we should move to `aiohttp` in a future PR as this library is all async except for a single method which is now not async that uses `requests`

Agreed, I think `aiohttp` is also more commonly used in HAs context. Plus, we already use it for [switcher_webapi](https://github.com/TomerFi/switcher_webapi).

Issue opened: https://github.com/TomerFi/aioswitcher/issues/794

**Comment by TomerFi** [comment]
> @TomerFi can you release a patch version with this fix? I will bump it in HA. Thanks

Yes, of course, I was just about to ask if I should. 😃

**Comment by TomerFi** [comment]
@allcontributors add @epenet for bug and code

**Comment by TomerFi** [comment]
@thecode 
Version [4.0.1](https://github.com/TomerFi/aioswitcher/releases/tag/4.0.1) released.

**Pull request merged**
