### PR TITLE
feat: adding Runner S11 to discovery with its states

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> FIRST MERGE THIS PR: https://github.com/TomerFi/aioswitcher/pull/649
This PR is based on the PR above.
This PR and branch are for adding Runner S11.
Until now, Runner S11 is able to be found by discovery and shows its current state with his lights state

## Checklist

- [X] I have followed this repository's contributing guidelines.
- [X] I will adhere to the project's code of conduct.

### CODE REVIEW

**Comment by TomerFi** [comment]
Thanks, but I may be missing something here.
Isn't S11 is the standard already supported runner?

**Comment by YogevBokobza** [comment]
> Thanks, but I may be missing something here. Isn't S11 is the standard already supported runner?

@TomerFi 
No it isn't.
Switcher have different devices called Runner:
1) Runner - https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-runner
2) Runner Mini - https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-runner-55
3) Runner S11 - https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/runner-lights-s11
4) Runner S12 - https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/runner-lights-s12

This librery only supports "Runner" and "Runner Mini", but does not support "Runner S11" and "Runner S12".

Runner S11 is one module contains "Runner" and 2 Switcher Lights (https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-light)

Runner S12 is one module contains 2 "Runner" and 1 Switcher Light (https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-light)

By the way, Switcher Light (https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-light) as separate is not supported here as well.

I personally have Runner S11 which is not supported by this librery and with this code I managed to find my device by Discovery script.

I am working now to solve its control part.

Yogev.

**Comment by YogevBokobza** [comment]
Also I decided to call this Runner S11 device: SHUTTER_SINGLE_LIGHT_DUAL
Representing Single Shutter and Dual Light

For Runner S12 device it will be: SHUTTER_DUAL_LIGHT_SINGLE
Representing Dual Shutter and Single Light

**Comment by TomerFi** [comment]
Let's put this PR on hold for now.
It will need rebasing and perhaps conflict resolutions after #649 gets merged.

**Comment by YogevBokobza** [comment]
@TomerFi 
I did rebase for this PR.
Continuing my work here.

**Comment by TomerFi** [comment]
> @TomerFi I did rebase for this PR. Continuing my work here.

Awesome, thank you.
Please click the remove from drafts when ready.

**Pull request closed without merging**
