### PR TITLE
chore: add poetry scripts

### PR DESCRIPTION
**Pull request by 5c077m4n**
## Description

In this PR I've wrapped the scripts in a `main` function to be able to call them from poetry without having to manually switch the python env

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
Thank you 🙏🏼 

(There are currently 2 failing test that fail on `dev` branch too)

### CODE REVIEW

**Comment by 5c077m4n** [comment]
Where can I find the PR title format?

**Comment by TomerFi** [comment]
> Where can I find the PR title format?

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by TomerFi** [comment]
I fixed the pr title, but I wouldn't type this "feat". I would go with "chore" or something because "feat" implies that a feature was added to the module and will increase the minor part of the version in the next bump.

Regardless, thank you very much for your contribution, I will review this later this week.

**Comment by 5c077m4n** [comment]
> I fixed the pr title, but I wouldn't type this "feat". I would go with "chore" or something because "feat" implies that a feature was added to the module and will increase the minor part of the version in the next bump.

Updated

**Review by YogevBokobza — APPROVED** [review]
Looks great to me :)

**Comment by TomerFi** [comment]
Thank you very much @5c077m4n !

**Comment by TomerFi** [comment]
@all-contributors add @5c077m4n for code

**Pull request merged**
