### PR TITLE
chore: fix yamllint warning

### LINKED ISSUE #490: Lint warning: yamlint warning  line too long
### What did you have in mind?

Release CI flow as a line which is too long that creates an error when running `yamlint`

### Are you trying to fix a problem?

When running poe lint the `yamlint` step reports a warning:
```txt
Poe => poetry run yamllint --format colored --strict .
.\.github\workflows\release.yml
  147:101   warning  line too long (101 > 100 characters)  (line-length)
```

### Any lead on how this feature can be implemented?

_No response_

### PR DESCRIPTION
**Pull request by thecode**
# Pull Request

> First PR? don't hesitate, push it.

## Description

> Describe what you did and why.

**Related issue (if any):** fixes https://github.com/TomerFi/aioswitcher/issues/490

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I have used the conventional commits specification for my commit messages.
- [x] I have signed my commits.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Review by TomerFi — COMMENTED** [review]
I don't think it will work the same,
the `>` will create one long line,
the `|` will create multiple lines.

if we have an issue with `yamllint` we can use: `# yamllint disable rule:...`

**Comment by thecode** [comment]
> I don't think it will work the same, the `>` will create one long line, the `|` will create multiple lines.

I used this to check: https://yaml-multiline.info/

> if we have an issue with `yamllint` we can use: `# yamllint disable rule:...`

`# yamllint disable rule:...` does not work for this since is not encapsulated with quotes, it did not remove the warning and I assume it takes it as part of the text.

**Comment by thecode** [comment]
Just realized that there is content bellow this line, will try another option

**Comment by thecode** [comment]
Turns out there was an extra (not needed) space there 😄 which was only needed to be removed.

**Review by TomerFi — APPROVED** [review]

**Pull request merged**
