### PR TITLE
Added a time_on field to state response

### PR DESCRIPTION
**Pull request by OrBin**
# Description
Added a time_on field in SwitcherV2StateResponseMSG to indicate how long is Switcher in "on" state.

### CODE REVIEW

**Comment by OrBin** [comment]
@TomerFi It seems like the build fails for stuff that's not related to my changes - missing pytest or yamllint. How should I respond to it?

**Comment by TomerFi** [comment]
@OrBin 

**Verify project with Python 3.8**
Was failing because a bug I remember seeing with `poetry` cache, I'll look up the link and share it.
The bug is just for the first run, the workaround is to restart the job.
I've restarted it, it's still failing, but now it's for a real `flake8` reason.

**Pull request triage**
Is failing because of some odd reason, I think it has something to do with the fact it's a forked repository.
I'll look it up, but no worries, It's just the PR triage, we can ignore it for now.

**Review by TomerFi — COMMENTED** [review]
Cool...

**Comment by OrBin** [comment]
Great!
I've also updated the docs but I was late for the merge, so I'll open another PR.
Also, I've added this field to switcher_webapi, so I'm about to open a PR for that too.

**Pull request merged**
