### PR TITLE
chore: stop shutter support for all known shutter devices

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Added DeviceType to all devices.
This is preparation for the new switcher devices that will be added.
Part one of splitting this PR https://github.com/TomerFi/aioswitcher/pull/694

This code is needed because the current state is that devices are defined as categories such as Runner, Power Plug, etc.
But there are different logic needed per specific devices such as Runner VS Runner S11.
This code will be able to determine different device types within the same category

BREAKING CHANGE: API users are now required to pass their device type as an argument

**Related issue (if any):** https://github.com/TomerFi/aioswitcher/pull/694

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by YogevBokobza** [comment]
@thecode  @TomerFi  As you wished, I made smaller PR and build it step by step

**Comment by TomerFi** [comment]
@thecode We currently don't have any active maintainers in this project. @YogevBokobza has generously offered to take on the maintaining responsibilities. And I appreciate that and happy to see him onboard. That being said, I wouldn't want his first contribution to this project to break HA integration.

Whenever you find the time, if you can please take a look and give your input, especially in regards to HA integration, this will be helpful. Once we get this feature merged and running, @YogevBokobza will become a maintainer in this project. I'll still stick around for helping out with deployments, dependency bumps and general stuff, but reviewing new features is a bit out-of-scope for me as I no longer use neither Switcher nor HA.

**Comment by TomerFi** [comment]
@YogevBokobza I reviewed this PR. Overall, I think it looks good. Good work. (Note the Py3.9 CI failure).
This is a breaking change right? We now require API users to pass their device type.

**Comment by YogevBokobza** [comment]
@TomerFi  Yes its breaking changes.
I can fix this in HA easy. Already has the code for that.
Will check the CI error

**Comment by YogevBokobza** [comment]
@TomerFi Fixed for python 3.9

**Comment by thecode** [comment]
> Whenever you find the time, if you can please take a look and give your input, especially in regards to HA integration, 

I will not be able to review PRs here, If I would I would probably also be a maintainer here. I don't have these types of devices so I can't confirm if they work correctly, I am not sure how it will work with the [switcher_webapi](https://github.com/TomerFi/switcher_webapi) Project.

This PR as it's own doesn't look like something that can't be adapted in HA, however I don't want @YogevBokobza to work for nothing so I will just mention that the token logic is not closed yet and will not be accepted in HA as it is currently implemented on https://github.com/TomerFi/aioswitcher/pull/694

Since there are devices which needs token and some don't the library should be able to determine if the device needs a token or not. We can't just ask users to add token if they don't need to.
When a token is added there should be a validation that the token is valid, I have not seen anything which validates the token and raise an exception when it is not valid. Since this is something which is copied over email or manually typed (not API based) it has more chances to be incorrect, but even for API based tokens HA requires that the user will be notified if the token is not valid.

**Comment by YogevBokobza** [comment]
> > Whenever you find the time, if you can please take a look and give your input, especially in regards to HA integration,
> 
> I will not be able to review PRs here, If I would I would probably also be a maintainer here. I don't have these types of devices so I can't confirm if they work correctly, I am not sure how it will work with the [switcher_webapi](https://github.com/TomerFi/switcher_webapi) Project.
> 
> This PR as it's own doesn't look like something that can't be adapted in HA, however I don't want @YogevBokobza to work for nothing so I will just mention that the token logic is not closed yet and will not be accepted in HA as it is currently implemented on #694
> 
> Since there are devices which needs token and some don't the library should be able to determine if the device needs a token or not. We can't just ask users to add token if they don't need to. When a token is added there should be a validation that the token is valid, I have not seen anything which validates the token and raise an exception when it is not valid. Since this is something which is copied over email or manually typed (not API based) it has more chances to be incorrect, but even for API based tokens HA requires that the user will be notified if the token is not valid.

Regarding this PR, I already have this working in HA as a PR.. The one that is opened there.
I just need to strip all the token logic from there to align it to here.
This library cannot know if device needs Token or not.
Token is based on devices and their firmware and this library cannot determine their firmware version.

Currently, Token is only required for Switcher Runner S11, S12 and Lights, but the plan is to use Token for all devices from some firmware version.
In HA we do ask people for Token and have a note when this Token is needed. This is the best we can do.
Regarding validation, it should be performed on the HA side.

**Comment by YogevBokobza** [comment]
@TomerFi @thecode 
Regarding This PR and [switcher_webapi](https://github.com/TomerFi/switcher_webapi)
I made this PR [#701](https://github.com/TomerFi/switcher_webapi/pull/701) in order to align the stuff also there.

**Comment by TomerFi** [comment]
> Yes its breaking changes.

@YogevBokobza
We auto bump our versions based on [the conventional commits spec](conventionalcommits.org), and we usually squash PRs. I've added a "_BREAKING CHANGE_" statement in the PR body to make it adhere the said spec. I also changed the PR title to make it a bit more clear as a commit message, please feel free to modify it again if I got the description wrong. I also wanted to mention [switcher_webapi](https://github.com/TomerFi/switcher_webapi) as the second known client of this project, and point out that this break must be addressed there too, but I see you already did that - Thank you!

@dmatik
You have always been very helpful and hands-on when it comes to this project and especially  [switcher_webapi](https://github.com/TomerFi/switcher_webapi), and this was always very much appreciated by all involved. So I wanted to ask your opinion in regards to the this breaking change and its reflection to Switcher WebAPI users.

---

> I will not be able to review PRs here, If I would I would probably also be a maintainer here.

@thecode
1) Although not officially supported by GitHub, it's quite common for community members to review PRs related to their specific knowledge and expertise by simply commenting in PR. As the sole maintainer of the HA integration and a formerly contributor to this project, you possess the required knowledge and expertise and your opinion was always very much appreciated.

2) Any contributor who wants to be a maintainer can simply ask to join, as stated in this project's README, this project requires new maintainers and contributors, anyone would be appreciated. My only request is that any new maintainer must first contribute something to the project. Obviously I cannot force any contributor to be a maintainer. So if one doesn't want - one will not be.

3) I know you're busy, and I know where you stand in regards to this project, that's why I didn't ask for a review directly (although one would be appreciated),  I asked for "_your input, especially in regards to HA integration_", which you shared with us in the next paragraph of your comment: "_This PR as it's own doesn't look like something that can't be adapted in HA_".
Thank you very much for your input!

---

@YogevBokobza
I've been meaning to ask you if this PR can stand on its own, or is it a part of an overall task that will be addressed in multiple PRs. If the latter is correct, than when merged, this should be merged into a target branch and not the main `dev` one.
Regardless to your answer, as I said in our private chat, the biggest client of this project is, AFAIK, Home Assistant. If HA can't get onboard with this, than we have a huge problem because we cannot break the HA integration. If it won't be feasible in HA, we might be forced into maintaining two PyPi modules, one for HA and one for Switcher WebAPI.

I do have to say, I agree with @thecode on the following comment: "_Since there are devices which needs token and some don't the library should be able to determine if the device needs a token or not. We can't just ask users to add token if they don't need to._". But I guess this should better asked in the next PR, as it doesn't seem like this one has anything to do with tokens yet.

**Comment by thecode** [comment]
> @thecode
> 3. I know you're busy, and I know where you stand in regards to this project, that's why I didn't ask for a review directly (although one would be appreciated),  I asked for "_your input, especially in regards to HA integration_", which you shared with us in the next paragraph of your comment: "_This PR as it's own doesn't look like something that can't be adapted in HA_".
>    Thank you very much for your input!

Thanks,
I will give input on the next PRs in this series, just can't commit to fully review the PRs, I still have on my backlog PRs for other integration+pypi which I am a single maintainer which are waiting too long.

I did a quick look on this PR and didn't find any show stopper.

**Comment by YogevBokobza** [comment]
@TomerFi 
Thanks for making progress here !! :)

Firstly, This PR is a first step in continuing progress to implement local-token based devices and then allow controlling devices such as Runner S11, S12, and Lights.

The next steps will be also committed in small as possible PRs until the whole logic is there.

I am focusing on making my changes across the board within this git repo, with [switcher_webapi](https://github.com/TomerFi/switcher_webapi) and with [HA](https://github.com/home-assistant/core)

Regarding "If HA can't get onboard with this, then we have a huge problem because we cannot break the HA integration." 
with all due respect to @thecode I disagree with the statement that token based-devices cannot be implemented in HA, As I already made it work with the whole logic inside [(#98596)](https://github.com/home-assistant/core/pull/98596) and it's fully tested with my own devices and I got many different Switcher devices.

So it's not a question of if this is possible but rather if I have the support from you and @thecode to continue with it to make the community happy by being able to use their Switcher devices.

I really need your support. It's not fun hitting "wall" and not making progress.
I am doing this in my free time just to please the HA community asking on Facebook and Discord "When Runner S11 will be supported? When Runner S12 will be supported?"

Thank you very much.

**Comment by thecode** [comment]
> Regarding "If HA can't get onboard with this, then we have a huge problem because we cannot break the HA integration."
> with all due respect to @thecode I disagree with the statement that token based-devices cannot be implemented in HA, As I already made it work with the whole logic inside [(#98596)](https://github.com/home-assistant/core/pull/98596) and it's fully tested with my own devices and I got many different Switcher devices.

I don't like this approach, if you want to get feedback or help from me try to think about my suggestions. When something is tested and working it doesn't mean it is accepted. I have reviewed more than 200 PRs in HA and read more than 1K reviews from others. When I wrote it won't be accepted it means that it doesn't qualify basic HA standards to give a good user experience.

I don't care if users are waiting for specific devices support or not, for Breeze we had a similar approach which needed API to the manufacture server for the device to work and while Switcher insisted this is the only possible way, together with @TomerFi  which asked us to try to avoid it and not let it go so fast eventually we are in a state that the device can work without connection to the manufacture server. The user experience is very different due to it, previously if we can't contact the server we can't init the device and the user needed to restart the integration when connection is restored (this is not something unusual, it can happen after power failure), now the integration works with Breeze even on isolated VLANs with no internet access.

For the token, we are 1 step back, we don't even use direct API to the manufacture server which would have be a better solution but we require the user to do a manual step.

HA doesn't require a token step to be automated, however it does require a way for the user to know if a token is needed. We can't just ask users to add a token, not get any feedback if it was needed, or if they copy the token correctly and let them pray that it will work. I may be wrong, but as far as I understand if it fails the logs will not tell us anything (because if they did we could also catch it and notify the user) so we are creating here future issues which will be hard to solve.

As far as I understand you can have a deterministic way to know if a device needs a token by implementing support for reading the FW version from the device and crossing it with the data you have from Switcher for which devices needs a token.

You can probably automatically validate this token by doing a "Get" API to the device and check if you get an answer, this way the device state will not change and you can inform the user if the token is valid, you may also use it to detect if devices needs a token, but since devices are detected asynchronously this will be complicated (but possible) to do it (there is a support for popping up a user intervention even after the integration was added and asking for additional data)

However all of my suggestions above are complicated to implement which is why I suggest you discuss with Switcher and find a better solution. If you follow the discussions here for Breeze you will see that we also thought it is impossible but the impossible did happen.

I am not 100% sure, but from issues in HA I understand that Switcher already require the user to enable local access for a device in their app (which is not needed for my devices, but other users stated that they can't control the device without it. If this is the case, they can notify the user in the App about the risks for local access (as they do when you request a token).

**Comment by YogevBokobza** [comment]
@thecode I hear you and your points and you are right in the most parts.
Right now getting the Token is only by manually reaching the link, entering the user's email, and the token is sent by email.
No API call for this at the moment..
Regarding knowing the firmware it's not possible either at the moment.. Perhaps Switcher can help with that.

@TomerFi Why did you change the base from "dev"? This PR can be merged and will work on its own.
Plus I will make sure this PR will not break anything by aligning the code in the other repo(as exists in the opened PR) that uses this and also in the HA repo.

If we put the whole logic in the same branch then we are back to one big PR to be merged later..

**Comment by TomerFi** [comment]
> Why did you change the base from "dev"? This PR can be merged and will work on its own.

@YogevBokobza
I asked "_if this PR can stand on its own, or is it a part of an overall task that will be addressed in multiple PRs_", you replied "_This PR is a first step in continuing progress to implement local-token based devices_". Did I misunderstood your intention?

I have to say, I agree with @thecode on this one. We should do everything we can to avoid a process where we depend on the vendor's API, website, or any other mean of contacting the vendor's servers. @thecode perfectly described the "Breeze situation", multiple people worked really hard to avoid these type processes when we had no clue if avoiding was even possible. Also @thecode is extremely experienced in HA integrations, if he says that this is not in the spirit of HA, he's probably right.

But, this PR is not yet implementing these token stuff, so perhaps it's best to discuss this someplace else. You said you already wrote the code, if so we can discuss this in the relevant PR, if you haven't started writing this yet, we can open a [discussion](https://github.com/TomerFi/aioswitcher/discussions) for this topic and discuss that before you write it.

I just want to make sure I get the point behind this specific PR before any merge:
- Can it stand by itself?
- Does it bring anything to the table? I mean, does it actually solves/adds something, or is it only required for the future steps?

**Comment by YogevBokobza** [comment]
@TomerFi
This PR can stand by itself.
The code here is helper for future but its working as standalone.
The code helps understand which specific device we are talking to and can be used for other purposes as well.

**Comment by TomerFi** [comment]
Got it. Thanks for the clarification.
If it's ok, I want to wait until tomorrow before merging, just to make sure @thecode or @dmatik don't have anything else to say in regards to this specific breaking change. If no one says anything, I'll merge this into the `dev` branch first thing tomorrow morning.

Thank you very much for your hard work!

**Review by TomerFi — DISMISSED** [review]

**Review by TomerFi — APPROVED** [review]

**Comment by thecode** [comment]
I don't have a problem if it is merged to the dev branch, however as you mentioned it doesn't bring anything new and I think some of the next PRs might be harder to merge directly into dev.

I think a better option is a dedicated working branch, when the final PR to dev is made it can be written that it is based on list of approved PRs (with the list of the PRs) without a full review (just checking that the CI pass).

However this is just my preference and anything you agree together that works best is fine by me.

**Comment by YogevBokobza** [comment]
@thecode
Normally it's possible what you are saying but because this library is shared in 2 different places (Docker API and HA) this will make things harder and will back to 1 big code change as we were before instead of smaller codes.

It would be a better idea to align the other 2 places as we go up with this library.
So every step this library goes the other 2 will follow.

**Comment by TomerFi** [comment]
@YogevBokobza 
I actually agree with @thecode on this.
That's why I asked _Does it bring anything to the table? I mean, does it actually solves/adds something, or is it only required for the future steps?_.

If this has no added value to the current project as-is, and it's simply required for the future steps, that this should go in a target branch and not the main one. There's no point in splitting 1 breaking change into multiple ones. And I don't want to block releases while waiting for the next steps.

**Comment by TomerFi** [comment]
Merged, please base all future PR against [runner-support](https://github.com/TomerFi/aioswitcher/tree/runner-support).

**Comment by TomerFi** [comment]
Discussion for this topic https://github.com/TomerFi/aioswitcher/discussions/715.

**Pull request merged**
