### PR TITLE
feat: add breeze update state

### PR DESCRIPTION
**Pull request by thecode**
Signed-off-by: thecode <levyshay1@gmail.com>

## Description

Add flag to update device state without controlling the device, used to sync the device by external state

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by TomerFi** [comment]
@thecode 
LGTM - added documentation for the new script argument in #573 .

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
PR title bot probably has a bug - ignoring it for now.

**Comment by TomerFi** [comment]
I think this can be merged.

**Comment by thecode** [comment]
Thanks!

**Pull request merged**
