### PR TITLE
feat: add Light sl03 support

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Add Switcher Light SL03 support
NOTE: First merge #805 

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
Thank you @YogevBokobza.
LGTM but I prefer @thecode to take a look before I merge.

**Review by thecode — APPROVED** [review]
Thanks @YogevBokobza

**Comment by TomerFi** [comment]
Release?

**Comment by YogevBokobza** [comment]
> Release?

Yes thanks!

**Comment by TomerFi** [comment]
[4.4.0](https://github.com/TomerFi/aioswitcher/releases/tag/4.4.0).

**Comment by TomerFi** [comment]
I want to work on the docs and improve them if I can. Do we know how many devices we have left that still need support?

**Comment by YogevBokobza** [comment]
> I want to work on the docs and improve them if I can. Do we know how many devices we have left that still need support?

Actually, that is it for now.
Switcher are working on 2 more devices but they are in pre-sale.
So we are good for now.

I do want to make one more PR to improve the coverage a little bit.. something I missed from previous PRs and just figure out.

**Comment by TomerFi** [comment]
NP - our work shouldn't conflict.
Thanks for the hard work; much appreciated!

**Comment by YogevBokobza** [comment]
> NP - our work shouldn't conflict. Thanks for the hard work; much appreciated!

No problem.. Glad I can help the community :)

**Pull request merged**
