### PR TITLE
fix: updated breeze codes and fix test

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Describe what you did and why.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by YogevBokobza** [comment]
@thecode Do You have a way to validate the DB against the issue opened?

**Comment by thecode** [comment]
While this is an updated database the relevant AC that was mentioned in #705 still not fixed
```json
    "SWTA7003": {
        "IRSetID": "SWTA7003",
        "OnOffType": 0,
        "IRWaveList": [
```

The `OnOffType` should be 1 for ACs that are using `Toggle` command (so that the device doesn't know if the AC is on or off and we add buttons to allow manual override of the device state.

I can't simply modify this file since the codes for the AC also needs to be changes.

While I have no objection to update the DB (and we should update it when we get a new one) I don't understand how it is not reflecting what the user see in Switcher App. If the App shows manual state override and user needs it (for ACs that has separate on of commands this is irrelevant anyhow so he wouldn't look for it) the file should also indicate the same.

**Review by thecode — APPROVED** [review]

**Comment by YogevBokobza** [comment]
> While this is an updated database the relevant AC that was mentioned in #705 still not fixed
> 
> ```json
>     "SWTA7003": {
>         "IRSetID": "SWTA7003",
>         "OnOffType": 0,
>         "IRWaveList": [
> ```
> 
> The `OnOffType` should be 1 for ACs that are using `Toggle` command (so that the device doesn't know if the AC is on or off and we add buttons to allow manual override of the device state.
> 
> I can't simply modify this file since the codes for the AC also needs to be changes.
> 
> While I have no objection to update the DB (and we should update it when we get a new one) I don't understand how it is not reflecting what the user see in Switcher App. If the App shows manual state override and user needs it (for ACs that has separate on of commands this is irrelevant anyhow so he wouldn't look for it) the file should also indicate the same.

Good point. I will ask the Switcher dev and update back.

**Comment by TomerFi** [comment]
[3.4.2](https://github.com/TomerFi/aioswitcher/releases/tag/3.4.2)

**Pull request merged**
