### PR TITLE
test: increased coverage to 100%

### PR DESCRIPTION
**Pull request by jafar-atili**
feat: added option to cache IRSet files

# Pull Request

> First PR? don't hesitate, push it.

## Description

 - Removed 2 exception handling from the code as its not possible to reach them (they are protected by inner calls)
 - Completed the tests to 100% code coverage
 - Added small feature which allows aioswitcher to save Breeze IRSet files in the host OS disk for caching them
 - Updated the Usage Examples in the README to include Breeze and Runner

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I have used the conventional commits specification for my commit messages.
- [x] I have signed my commits.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Fixed comment in the code that listed the Heater as Type2 device

### CODE REVIEW

**Comment by jafar-atili** [comment]
I tested flake8/black/spelling locally, all passed.
I'll be happy if you can start the Workflow.

**Comment by TomerFi** [comment]
https://github.com/TomerFi/aioswitcher/blob/dev/.github/CONTRIBUTING.md#get-started

**Comment by jafar-atili** [comment]
> https://github.com/TomerFi/aioswitcher/blob/dev/.github/CONTRIBUTING.md#get-started

Thank you.
All the poe passed now, only those two failing:

* `poe sphinx_spelling`
* `poe sphinx_build`

```
Poe => sphinx-build -b singlehtml docs docsbuild

  FileNotFoundError

  [Errno 2] No such file or directory: b'/Library/Frameworks/Python.framework/Versions/3.7/bin/sphinx-build'

  at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

**Comment by TomerFi** [comment]
> All the poe passed now, only those two failing:
> 
> * `poe sphinx_spelling`
> * `poe sphinx_build`

@jafar-atili 
Please run `poe install_docs` first to install the required deps for the docs,
and then these two should work.

Although these won't fail the PR workflows, they will fail the staging and releasing workflows,
so if they are any errors produced by these two, we'll probably be better off handling them with this PR.

EDIT:
You can use this for unknown words:
https://github.com/TomerFi/aioswitcher/blob/dev/docs/spelling_wordlist.txt

**Comment by TomerFi** [comment]
@jafar-atili 
For future PRs, please use a different branch name than the branch you're PRing against.
It creates multiple tracking branches when working with the CLI.

**Review by thecode — APPROVED** [review]

**Comment by TomerFi** [comment]
@thecode I think we should wait with this PR until we address https://github.com/TomerFi/aioswitcher/pull/508#issuecomment-1172902080, `poe sphinx_spelling` fails.

**Comment by jafar-atili** [comment]
> > All the poe passed now, only those two failing:
> > 
> > * `poe sphinx_spelling`
> > * `poe sphinx_build`
> 
> @jafar-atili Please run `poe install_docs` first to install the required deps for the docs, and then these two should work.
> 
> Although these won't fail the PR workflows, they will fail the staging and releasing workflows, so if they are any errors produced by these two, we'll probably be better off handling them with this PR.
> 
> EDIT: You can use this for unknown words: https://github.com/TomerFi/aioswitcher/blob/dev/docs/spelling_wordlist.txt


I don't understand what is expected? 

```
Poe => sphinx-build -b spelling docs docsbuild
Running Sphinx v4.2.0
loading translations [en]... done
Initializing Spelling Checker 7.2.1
loading pickled environment... done
Ignoring wiki words
Ignoring acronyms
Ignoring Python builtins
Ignoring importable module names
Ignoring contributor names
Looking for custom word list in /Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/spelling_wordlist.txt
Scanning contributors
building [mo]: targets for 0 po files that are out of date
building [spelling]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/codedocs.rst: Spell check: SwitcherThermostatStateResponse: aioswitcher.api.messages.SwitcherThermostatStateResponse.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/codedocs.rst: Spell check: SwitcherShutterStateResponse: aioswitcher.api.messages.SwitcherShutterStateResponse.
Writing /Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docsbuild/codedocs.spelling
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: qualcomm: Protocol type 1 (UDP port 20002), used by: Switcher Mini, Switcher Power Plug, Switcher Touch, Switcher V2 (esp), Switcher V2 (qualcomm), Switcher V4.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: DeviceState: thermostat state, possible values: {'on': <DeviceState.ON: ('01', 'on')>, 'off': <DeviceState.OFF: ('00', 'off')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: DeviceState: thermostat state, possible values: {'on': <DeviceState.ON: ('01', 'on')>, 'off': <DeviceState.OFF: ('00', 'off')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatMode: thermostat mode, possible values: {'auto': <ThermostatMode.AUTO: ('01', 'auto')>, 'dry': <ThermostatMode.DRY: ('02', 'dry')>, 'fan': <ThermostatMode.FAN: ('03', 'fan')>, 'cool': <ThermostatMode.COOL: ('04', 'cool')>, 'heat': <ThermostatMode.HEAT: ('05', 'heat')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatMode: thermostat mode, possible values: {'auto': <ThermostatMode.AUTO: ('01', 'auto')>, 'dry': <ThermostatMode.DRY: ('02', 'dry')>, 'fan': <ThermostatMode.FAN: ('03', 'fan')>, 'cool': <ThermostatMode.COOL: ('04', 'cool')>, 'heat': <ThermostatMode.HEAT: ('05', 'heat')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatMode: thermostat mode, possible values: {'auto': <ThermostatMode.AUTO: ('01', 'auto')>, 'dry': <ThermostatMode.DRY: ('02', 'dry')>, 'fan': <ThermostatMode.FAN: ('03', 'fan')>, 'cool': <ThermostatMode.COOL: ('04', 'cool')>, 'heat': <ThermostatMode.HEAT: ('05', 'heat')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatMode: thermostat mode, possible values: {'auto': <ThermostatMode.AUTO: ('01', 'auto')>, 'dry': <ThermostatMode.DRY: ('02', 'dry')>, 'fan': <ThermostatMode.FAN: ('03', 'fan')>, 'cool': <ThermostatMode.COOL: ('04', 'cool')>, 'heat': <ThermostatMode.HEAT: ('05', 'heat')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatMode: thermostat mode, possible values: {'auto': <ThermostatMode.AUTO: ('01', 'auto')>, 'dry': <ThermostatMode.DRY: ('02', 'dry')>, 'fan': <ThermostatMode.FAN: ('03', 'fan')>, 'cool': <ThermostatMode.COOL: ('04', 'cool')>, 'heat': <ThermostatMode.HEAT: ('05', 'heat')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatFanLevel: thermostat fan level, possible values: {'low': <ThermostatFanLevel.LOW: ('1', 'low')>, 'medium': <ThermostatFanLevel.MEDIUM: ('2', 'medium')>, 'high': <ThermostatFanLevel.HIGH: ('3', 'high')>, 'auto': <ThermostatFanLevel.AUTO: ('0', 'auto')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatFanLevel: thermostat fan level, possible values: {'low': <ThermostatFanLevel.LOW: ('1', 'low')>, 'medium': <ThermostatFanLevel.MEDIUM: ('2', 'medium')>, 'high': <ThermostatFanLevel.HIGH: ('3', 'high')>, 'auto': <ThermostatFanLevel.AUTO: ('0', 'auto')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatFanLevel: thermostat fan level, possible values: {'low': <ThermostatFanLevel.LOW: ('1', 'low')>, 'medium': <ThermostatFanLevel.MEDIUM: ('2', 'medium')>, 'high': <ThermostatFanLevel.HIGH: ('3', 'high')>, 'auto': <ThermostatFanLevel.AUTO: ('0', 'auto')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatFanLevel: thermostat fan level, possible values: {'low': <ThermostatFanLevel.LOW: ('1', 'low')>, 'medium': <ThermostatFanLevel.MEDIUM: ('2', 'medium')>, 'high': <ThermostatFanLevel.HIGH: ('3', 'high')>, 'auto': <ThermostatFanLevel.AUTO: ('0', 'auto')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatSwing: thermostat swing, possible values: {'off': <ThermostatSwing.OFF: ('0', 'off')>, 'on': <ThermostatSwing.ON: ('1', 'on')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatSwing: thermostat swing, possible values: {'off': <ThermostatSwing.OFF: ('0', 'off')>, 'on': <ThermostatSwing.ON: ('1', 'on')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatSwing: thermostat temperature, possible values: {'off': <ThermostatSwing.OFF: ('0', 'off')>, 'on': <ThermostatSwing.ON: ('1', 'on')>}.
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: ThermostatSwing: thermostat temperature, possible values: {'off': <ThermostatSwing.OFF: ('0', 'off')>, 'on': <ThermostatSwing.ON: ('1', 'on')>}.
Writing /Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docsbuild/scripts.spelling
writing output... [100%] usage                                                                                                                      
WARNING: Found 18 misspelled words
build succeeded, 1 warning.
```

**Comment by TomerFi** [comment]
> WARNING: Found 18 misspelled words

In the following example from the log you attached:
```
/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1: Spell check: qualcomm: Protocol type 1 (UDP port 20002), used by: Switcher Mini, Switcher Power Plug, Switcher Touch, Switcher V2 (esp), Switcher V2 (qualcomm), Switcher V4.
```

`/Users/jafaratili/Documents/Projects/aioswitcher2/aioswitcher/docs/scripts.rst:1:`
is the line where the spelling mistake was found.

`Spell check: qualcomm:`
qualcomm is the misspelled word.

`Protocol type 1 (UDP... Switcher V2 (qualcomm)...`
is the sentence where the spelling mistake was found.

I this is a mistake and this infect is the correct spelling,
you can add `qualcomm` to [spelling_wordlist.txt](https://github.com/TomerFi/aioswitcher/blob/dev/docs/spelling_wordlist.txt) for the spelling plugin to ignore it.

Edit:
Note that `docs/scripts.rst:1` leads to a `sphinx` directive that creates docs from code comments, so the actual misspelled word is actually in the code.

**Comment by jafar-atili** [comment]
Maybe the word qualcomm in the comment does not add any value and can be removed, however the rest complaining on Class naming which basically following the flake8/pep convention and I don't see how to improve that.

Do you see other way than excluding them?

**Comment by TomerFi** [comment]
> Maybe the word qualcomm in the comment does not add any value and can be removed, however the rest complaining on Class naming which basically following the flake8/pep convention and I don't see how to improve that.
> 
> Do you see other way than excluding them?

As I said above, use [spelling_wordlist.txt](https://github.com/TomerFi/aioswitcher/blob/dev/docs/spelling_wordlist.txt) for ignoring words.

EDIT:
Just add the following lines to docs/spelling_wordlist.txt and you should be good to go:
```text
SwitcherThermostatStateResponse
SwitcherShutterStateResponse
qualcomm
DeviceState
ThermostatMode
ThermostatFanLevel
ThermostatSwing
```

**Pull request merged**
