### PR TITLE
chore: bump min py to 3.12 and publish py to 3.13

### LINKED ISSUE #818: Consider python bump
### What did you have in mind?

Our default Python version is 3.10. In CI, we build for 3.9 and 3.10. The current major is 3.13. Should we bump?

@thecode Do you happen to know what version is used/supported by Home Assitant?

### Are you trying to fix a problem?

_No response_

### Any lead on how this feature can be implemented?

_No response_

### PR DESCRIPTION
**Pull request by TomerFi**
## Description

BREAKING CHANGE: The minimum Python requirement is now 3.12.

This commit also includes a couple of adjustments to the cached environments in the CI.

fixes: #818

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

### CODE REVIEW

**Review by thecode — APPROVED** [review]
Thanks @TomerFi

**Comment by TomerFi** [comment]
@thecode Does this qualify for a major or a minor bump?

**Comment by thecode** [comment]
> @thecode Does this qualify for a major or a minor bump?

I think due to the drop of older Python support we should do a major bump, although there is nothing breaking in this release, but it will be better showing that this may break in the future (since we don't run CI on older releases)

**Comment by TomerFi** [comment]
Version [6.0.0](https://github.com/TomerFi/aioswitcher/releases/tag/6.0.0).

**Pull request merged**
