### PR TITLE
chore: future merge rebased version of runner-support

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

>  Runner support. to be merged in the future.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by thecode** [comment]
For future issues like this would be better to fix the rebase issue (usually @TomerFi can help with that) since we now lost the tracking and discussion/comments.

Before reviewing this PR we still need to finalize the discussion at https://github.com/TomerFi/aioswitcher/discussions/715

**Comment by thecode** [comment]
I understand that #747 is based on this PR, can we close this PR?

**Comment by YogevBokobza** [comment]
> I understand that #747 is based on this PR, can we close this PR?

I believe this is @TomerFi's idea, so we can merge all the small changes to this Branch/PR and merge it as a whole to the "dev" branch.
So it should stay open.

**Comment by thecode** [comment]
That was my idea, but the idea was to merge to a branch, not to create a PR to dev, you deleted the branch already so there is no point in this PR anymore

**Comment by YogevBokobza** [comment]
> That was my idea, but the idea was to merge to a branch, not to create a PR to dev, you deleted the branch already so there is no point in this PR anymore

This branch "runner-support-fixed" will eventually be merged to the "dev" branch.
The Runner S11 PR will join this one and from here we can merge it to "dev".

Leaving this PR open helps me better sync the "dev" branch tho this and from this to the Runner S11 branch.

**Comment by TomerFi** [comment]
Please re-open or open a new version of this PR once it's ready to be reviewed.

**Pull request closed without merging**
