### PR TITLE
Updated docs

### LINKED ISSUE #563: Remove usage of get_event_loop from the docs
### What did you have in mind?

In #561 we removed the usage of `get_event_loop` from our code.
We should also remove it from our documentation site and repo readme.

### Are you trying to fix a problem?

_No response_

### Any lead on how this feature can be implemented?

_No response_

### PR DESCRIPTION
**Pull request by Kesav890**
# Pull Request

> First PR? don't hesitate, open it.

## Description

> removed get_event_loop() in docs and repo readme

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I have used the conventional commits specification for my commit messages.
- [x] I have signed my commits.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Review by oranja — COMMENTED** [review]
asyncio usage looks good 👍🏼

**Comment by Kesav890** [comment]
what to do with the errors?

**Comment by TomerFi** [comment]
[conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
see [run info](https://github.com/TomerFi/aioswitcher/pull/565/checks?check_run_id=8798049052).

You'll need to update the messages in the commits to fit the conventional commits specifications, we bump version based on this.

Try something like: `docs: update asyncio invocations in README`, instead of `Update README.md`.
and `docs: update asyncio invocation in doc examples`, instead of `Update usage.md`.
You can even combine both commits to one if you want.

Ping me if you need further guidance on this.

**Comment by TomerFi** [comment]
@Kesav890 assuming _origin_ is the name of you forked remote, this should do the trick:

```shell
git checkout updated-docs
git reset a9825ae4
git add README.md docs/usage.md
git commit -sm "docs: update asyncio invocation in doc examples"
git push origin HEAD
```

**Comment by TomerFi** [comment]
@all-contributors add @Kesav890 for doc

**Comment by Kesav890** [comment]
@TomerFi thankyou

**Comment by TomerFi** [comment]
Thank you for your contribution.

**Pull request merged**
