### PR TITLE
feat: runner s11 integration

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

BREAKING CHANGES:
- SwitcherApi require new parameter - device_type
- Shutter API "stop" replaced with "stop_shutter".

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by YogevBokobza** [comment]
@thecode @TomerFi 
I think we are finally ready to merge this S11 integration..
I don't think anything is left.. I tested everything from my end and it looks like its working..
I will do a few more tests while you are reviewing it.

**Review by thecode — DISMISSED** [review]
Looks good, Thanks!

**Comment by YogevBokobza** [comment]
@TomerFi Approve to merge?

**Comment by TomerFi** [comment]
> @TomerFi Approve to merge?

I prefer to take a look before, to make sure we didn't miss anything.

**Comment by YogevBokobza** [comment]
> > @TomerFi Approve to merge?
> 
> I prefer to take a look before, to make sure we didn't miss anything.

Please finish your review soon.. I already started to make progress in implementing those changes to the HA
as seen here: https://github.com/home-assistant/core/pull/122404
The current code tested working perfectly in HA controlling my devices which are Switcher Runner Mini, Switcher Runner S11, Switcher Mini, Switcher Power Plug, Switcher Breeze

**Comment by YogevBokobza** [comment]
> > > @TomerFi Approve to merge?
> > 
> > 
> > I prefer to take a look before, to make sure we didn't miss anything.
> 
> Please finish your review soon.. I already started to make progress in implementing those changes to the HA as seen here: [home-assistant/core#122404](https://github.com/home-assistant/core/pull/122404) The current code tested working perfectly in HA controlling my devices which are Switcher Runner Mini, Switcher Runner S11, Switcher Mini, Switcher Power Plug, Switcher Breeze

Made progress here too: https://github.com/TomerFi/switcher_webapi/pull/715

**Comment by TomerFi** [comment]
@YogevBokobza 
Yep, sorry I was away. Let's merge this!
We need the title of the PR to start with "feat" and the body of the PR to include "BREAKING CHANGES:" and will include a list of what we broke, i.e. "API not takes type."
These will affect the version bump.

**Comment by YogevBokobza** [comment]
@TomerFi @thecode 
I changed the title and fixed the description.

I also opened this [PR ](https://github.com/TomerFi/aioswitcher/pull/782) with small fixes.
We can merge this PR and after that the other one or vice versa..
Your choice..

**Comment by thecode** [comment]
@YogevBokobza 
> BREAKING CHANGES:
> - API does not take type (device_type)..

Can you explain this?

> - If calling Shutter or Light operations with a Switcher Runner S11 device, a token must be specified.

This is a new device so it is not under breaking changes, it will not break anything for existing users.

> - self._login function no longer called with DeviceType parameter, now only self._login()

This is an internal change, `self._login` is not exposed to users and should not be listed under breaking changes.

**Comment by YogevBokobza** [comment]
> @YogevBokobza
> 
> > BREAKING CHANGES:
> > 
> > * API does not take type (device_type)..
> 
> Can you explain this?
> 
> > * If calling Shutter or Light operations with a Switcher Runner S11 device, a token must be specified.
> 
> This is a new device so it is not under breaking changes, it will not break anything for existing users.
> 
> > * self._login function no longer called with DeviceType parameter, now only self._login()
> 
> This is an internal change, `self._login` is not exposed to users and should not be listed under breaking changes.

I removed the last 2 from the breakchanges..
Regarding the first one here is an example: https://github.com/TomerFi/aioswitcher/pull/780/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R42
now need to supply the device_type

**Comment by thecode** [comment]
> I removed the last 2 from the breakchanges.. Regarding the first one here is an example: https://github.com/TomerFi/aioswitcher/pull/780/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R42 now need to supply the device_type

You wrote "API does not take type (device_type)", but the change introduce a new parameter `device_type`. The message should be:
`SwitcherApi` require new parameter - `device_type`

**Comment by YogevBokobza** [comment]
> > I removed the last 2 from the breakchanges.. Regarding the first one here is an example: https://github.com/TomerFi/aioswitcher/pull/780/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R42 now need to supply the device_type
> 
> You wrote "API does not take type (device_type)", but the change introduce a new parameter `device_type`. The message should be: `SwitcherApi` require new parameter - `device_type`

Accepted and replaced.

**Review by TomerFi — DISMISSED** [review]

**Comment by TomerFi** [comment]
@thecode @YogevBokobza 
Can I merge?

**Comment by TomerFi** [comment]
Merging https://github.com/TomerFi/aioswitcher/pull/782 first!

**Review by TomerFi — APPROVED** [review]

**Comment by YogevBokobza** [comment]
> @thecode @YogevBokobza Can I merge?

@TomerFi I think we can merge.. @thecode already approved this PR before the last PR merge and approved the last PR

**Comment by TomerFi** [comment]
I assume you're right, still, I prefer to wait for @thecode to approve again because I noticed some related discussion you guys had in another issue.

**Comment by YogevBokobza** [comment]
> I assume you're right, still, I prefer to wait for @thecode to approve again because I noticed some related discussion you guys had in another issue.

This PR is not related to the issue mentioned.
The logic here for the Switcher Runner (normal) have not been changed.
For my Switcher Runner devices (Mini, S11) it's working.
The Switcher Runner Mini has the same logic as Switcher Runner. So no change here.

My guess with his issue is old firmware of his Switcher device or his device itself have some kind of problem.

**Review by thecode — APPROVED** [review]

**Comment by thecode** [comment]
> My guess with his issue is old firmware of his Switcher device or his device itself have some kind of problem.

This PR can be merged, but I prefer we fix the Runner before a new release. The firmware version of his device is not related.

**Comment by TomerFi** [comment]
> This PR can be merged, but I prefer we fix the Runner before a new release. The firmware version of his device is not related.

Merged. It has not been released yet. I assume https://github.com/TomerFi/aioswitcher/issues/783 is the issue in question.

@YogevBokobza @thecode 
Thank you both for this fantastic work and collaboration; I apologize for being absent at times.
❤️

**Pull request merged**
