### PR TITLE
chore: remove requests and replace with aiohttp

### LINKED ISSUE #794: Replace requests with aiohttp
### What did you have in mind?

Replace `requests` with `aiohttp`.
See https://github.com/TomerFi/aioswitcher/pull/792#pullrequestreview-2233072471 .

We already use `aiohttp` for the [switcher_webapi](https://github.com/TomerFi/switcher_webapi) project.

### Are you trying to fix a problem?

_No response_

### Any lead on how this feature can be implemented?

_No response_

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Remove requests and replace with aiohttp

**Related issue (if any):** fixes [#794](https://github.com/TomerFi/aioswitcher/issues/794)

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Review by TomerFi — DISMISSED** [review]

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
Thank you @YogevBokobza .
cc @thecode .

**Comment by TomerFi** [comment]
@thecode If you haven't updated HA with 4.0.1 yet, we can release 4.0.2, including this.

**Comment by YogevBokobza** [comment]
> @thecode If you haven't updated HA with 4.0.1 yet, we can release 4.0.2, including this.

He did update HA already, but this PR is important to me for the S11 HA integration so make a release for it.

**Comment by thecode** [comment]
If you make a new release I can make the PR to bump it in HA

**Comment by YogevBokobza** [comment]
> If you make a new release I can make the PR to bump it in HA

Please do it :)

**Comment by TomerFi** [comment]
[4.0.2](https://github.com/TomerFi/aioswitcher/releases/tag/4.0.2) released.

**Pull request merged**
