### PR TITLE
feat: allow passing client session

### PR DESCRIPTION
**Pull request by thecode**
Signed-off-by: thecode <levyshay1@gmail.com>

# Pull Request

> First PR? don't hesitate, push it.

## Description

> Describe what you did and why.

Allow passing external client session for HTTP request, required by HA:
https://developers.home-assistant.io/docs/integration_quality_scale_index/#platinum-

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I have used the conventional commits specification for my commit messages.
- [x] I have signed my commits.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?
>

### CODE REVIEW

**Review by jafar-atili — APPROVED** [review]

**Review by TomerFi — DISMISSED** [review]

**Comment by TomerFi** [comment]
@thecode 
LGTM, but we need to fix the failing test first.

**Comment by thecode** [comment]
> Owner

There are no failing tests in this PR. If fails on coverage do to the main merged PR which @jafar-atili already addressed in a PR. Running this change over his PR will pass. We can first merge the tests PR (https://github.com/TomerFi/aioswitcher/pull/493) and rebase this PR.

**Comment by TomerFi** [comment]
> > Owner
> 
> There are no failing tests in this PR. If fails on coverage do to the main merged PR which @jafar-atili already addressed in a PR. Running this change over his PR will pass. We can first merge the tests PR (#493) and rebase this PR.

https://github.com/TomerFi/aioswitcher/pull/493 is merged please resolve the conflicts.

**Comment by TomerFi** [comment]
The tests are still failing and it doesn't look like a coverage threshold issue this time:
image

**Review by TomerFi — APPROVED** [review]

**Pull request merged**
